definitions:
  main.Entry:
    properties:
      author:
        type: string
      content:
        type: string
      id:
        type: string
      title:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/entries:
    post:
      consumes:
      - application/json
      description: Create a new entry with the provided data
      parameters:
      - description: Entry object
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/main.Entry'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/main.Entry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new entry
      tags:
      - entries
  /api/entries/{id}:
    get:
      consumes:
      - application/json
      description: Get a single entry by its ID
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Entry'
        "404":
          description: Not Found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get an entry by ID
      tags:
      - entries
    put:
      consumes:
      - application/json
      description: Update an entry by its ID with the provided data
      parameters:
      - description: Entry ID
        in: path
        name: id
        required: true
        type: string
      - description: Entry object
        in: body
        name: entry
        required: true
        schema:
          $ref: '#/definitions/main.Entry'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Entry'
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Update an existing entry
      tags:
      - entries
  /api/search:
    get:
      consumes:
      - application/json
      description: Search entries by query string
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Entry'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search entries
      tags:
      - search
swagger: "2.0"
