definitions:
  domain.News:
    properties:
      author_id:
        type: string
      content:
        type: string
      created_at:
        type: string
      id:
        type: string
      image_url:
        type: string
      tags:
        items:
          type: string
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/search:
    get:
      consumes:
      - application/json
      description: Search news content with boosted results for specified author
      parameters:
      - description: Search query
        in: query
        name: q
        required: true
        type: string
      - description: Author username to boost results for
        in: query
        name: username
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/domain.News'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search news with author boosting
      tags:
      - search
swagger: "2.0"
